kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "simple-cloud-provider.fullname" . }}
  labels:
    {{- include "simple-cloud-provider.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "simple-cloud-provider.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "simple-cloud-provider.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
