apiVersion: v1
kind: ConfigMap
metadata:
  name: simple-cloud-provider
  namespace: kube-system
  labels:
    {{- include "simple-cloud-provider.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.config | nindent 2 }}
